site_name: My Space
site_url: https://kaunghtetminkght-prog.github.io/mk-docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.footer   # 👈 PREVIOUS / NEXT BUTTONS

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaunghtetminkght-prog

copyright: '© 2026 Your Name'

# 👇 ADD THIS TO CONTROL THE ORDER OF YOUR PAGES
nav:
  - Home: index.md
  # - About: about.md
  # - Contact: contact.md
  # Add your other pages here in the order you want them to appear.
